#include <iostream>
#include <vector>
#include <cmath>
#include "TFile.h"
#include "TTree.h"
#include "fastjet/ClusterSequence.hh"

using namespace std;
using namespace fastjet;

int main() {
    // 1. Open the ROOT file generated by Pythia
    TFile *f = TFile::Open("full_history_pythia.root");
    if (!f || f->IsZombie()) {
        cerr << "Error: Could not open full_history_pythia.root!" << endl;
        return 1;
    }

    TTree *t = (TTree*)f->Get("ParticleTree");

    int EventID, ParticleID, Index;
    bool IsFinal;
    double Px, Py, Pz, Energy;

    t->SetBranchAddress("EventID", &EventID);
    t->SetBranchAddress("Index", &Index);
    t->SetBranchAddress("ParticleID", &ParticleID);
    t->SetBranchAddress("IsFinal", &IsFinal);
    t->SetBranchAddress("Px", &Px);
    t->SetBranchAddress("Py", &Py);
    t->SetBranchAddress("Pz", &Pz);
    t->SetBranchAddress("Energy", &Energy);

    vector<PseudoJet> input_particles;
    int eventToShow = 0; // Reconstructing Event 0

    Long64_t nentries = t->GetEntries();
    for (Long64_t i = 0; i < nentries; i++) {
        t->GetEntry(i);

        // Filter: Only look at Event 0
        if (EventID != eventToShow) continue;
        
        // Filter: Jets are only built from stable, final-state particles
        if (!IsFinal) continue; 

        int absPDG = abs(ParticleID);
        // Filter: Detectors cannot see neutrinos, so they do not go into jet reconstruction
        if (absPDG == 12 || absPDG == 14 || absPDG == 16) continue;

        // Convert ROOT kinematics into FastJet PseudoJet objects
        PseudoJet particle(Px, Py, Pz, Energy);
        
        // Store the original Particle ID inside the FastJet object for later reference
        particle.set_user_index(ParticleID); 
        
        input_particles.push_back(particle);
    }
    f->Close();

    // 2. Setup FastJet Clustering
    // Anti-kt algorithm with a radius parameter R = 0.4 (The standard at the LHC)
    double R = 0.4;
    JetDefinition jet_def(antikt_algorithm, R);

    // Run the clustering sequence
    ClusterSequence cs(input_particles, jet_def);

    // Extract jets with transverse momentum (pT) > 20 GeV
    double ptmin = 20.0;
    vector<PseudoJet> jets = sorted_by_pt(cs.inclusive_jets(ptmin));

    // 3. Print the Results
    cout << "========================================" << endl;
    cout << " FastJet Reconstruction for Event " << eventToShow << endl;
    cout << "========================================" << endl;
    cout << "Algorithm: " << jet_def.description() << endl;
    cout << "Found " << jets.size() << " jets with pT > " << ptmin << " GeV.\n" << endl;
    
    printf("%5s %15s %15s %15s %15s\n", "Jet #", "pT (GeV)", "Rapidity", "Phi", "Constituents");
    cout << "-------------------------------------------------------------------" << endl;
    
    for (unsigned i = 0; i < jets.size(); i++) {
        printf("%5u %15.3f %15.3f %15.3f %15zu\n",
               i, jets[i].pt(), jets[i].rap(), jets[i].phi(),
               jets[i].constituents().size());
    }

    return 0;
}